class Solution {
public:
    int lastStoneWeightII(vector<int>& stones) {
        if(stones.size()==1) return stones[0];
        int sum=0;
        int n=stones.size();
        for(int i=0;i<stones.size();i++)
        {
            sum=sum+stones[i];
        }
        bool dp[n][sum+1];
        memset(dp,false,sizeof(dp));
        dp[0][stones[0]]=true;
        for(int i=1;i<n;i++)
        {
            for(int j=0;j<=sum;j++)
            {
                if(dp[i-1][j])// this has been generated by array elements
                {
                    dp[i][j+stones[i]]=true;
                    dp[i][abs(j-stones[i])]=true;
                }
            }
        }
        int ans;
        // least element generated by n-1 elemnts of array
        for(int i=0;i<=sum;i++)
        {
            if(dp[n-1][i]) {ans=i;break;}
        }
        return ans;
    }
};
